spring:
  thymeleaf:
    # ????
    cache: false
  # ?????
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/seckill
    username: root
    password: 456123
    hikari:
      # ?????
      pool-name: hjhikaricp
      # ???????
      minimum-idle: 5
      # ?????????????600000?????
      idle-timeout: 1800000
      # ????????10
      maximum-pool-size: 10
      # ????
      auto-commit: true
      # ???????????180000?30???
      max-lifetime: 1800000
      # ?????????30000?30??
      connection-timeout: 30000
      # ?????????????
      connection-test-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 100
        #最小空闲连接
        min-idle: 5
# mybatis-plus??
mybatis-plus:
  # ??mapper.xml????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # ??mybatis???????????????
  type-aliases-package: com.xxxx.seckill.pojo

# sql??????????????mapper.xml?????
logging:
  level:
    com.hj.seckill.pojo: debug
